/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    BasicForm: typeof import('./components/BasicForm.vue')['default']
    DocumentCard: typeof import('./components/DocumentCard.vue')['default']
    DocumentList: typeof import('./components/DocumentList.vue')['default']
    Form: typeof import('./components/Form.vue')['default']
    FullForm: typeof import('./components/FullForm.vue')['default']
    HelloWorld: (typeof import('./components/HelloWorld.vue'))['default']
    Navbar: typeof import('./components/navigation/Navbar.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/navigation/Sidebar.vue')['default']
  }
}
